# config/routes.yaml
lucky_number:
    path: /lucky/numberone
    # the controller value has the format 'controller_class::method_name'
    controller: App\Controller\LuckyController::number

    # if the action is implemented as the __invoke() method of the
    # controller class, you can skip the '::method_name' part:
    # controller: App\Controller\BlogController

create_product:
    path: /create/product
    controller: App\Controller\ProductController::createProduct
    methods: POST